### ISSUE TITLE
Error while load model

### ISSUE THREAD

**Issue by paopaofeiniu** [liortalker/MindTheEdge#3]
Hi, an error occurred when I was using the downloaded pre-trained model. I didn't change any files and this is the result I get:

# python infer_edges.py --config 'packnet_code/configs/infer_packnet_kitti.yaml'
### Preparing Model
Model: SemiSupEdgeModel
DepthNet: PackNetSAN01
Traceback (most recent call last):
  File "infer_edges.py", line 408, in <module>
    main(sys.argv[1:])
  File "infer_edges.py", line 118, in main
    infer_and_save_depth(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "infer_edges.py", line 332, in infer_and_save_depth
    pred_inv_depth = model_wrapper.depth(image, rgb_edge=rgb_edge_image)['inv_depths'][0][0]
  File "/workspace/MindTheEdge/packnet_code/packnet_sfm/models/model_wrapper.py", line 321, in depth
    return self.depth_net(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/MindTheEdge/packnet_code/packnet_sfm/networks/depth/PackNetSAN01.py", line 283, in forward
    return_arr = self.run_network(rgb_encoder_input, input_depth)
  File "/workspace/MindTheEdge/packnet_code/packnet_sfm/networks/depth/PackNetSAN01.py", line 267, in run_network
    if self.is_depth_aux_net:
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PackNetSAN01' object has no attribute 'is_depth_aux_net'

**Comment by liortalker** [comment]
Hi,
Sorry for this error. I fixed the issue. Please pull and try again.
Tell me if you have further problems.

**Comment by paopaofeiniu** [comment]
The problem has been resolved.
Thank you very much!
